### ISSUE TITLE
Heuristic for near goal [node3d]

### ISSUE THREAD

**Issue by SteveMacenski** [SteveMacenski/navigation2#7]
We need to have a precomputed table of heuristic values for bins around the goal. This kinematically aware but cost unaware heuristic will be combined with the L2 norm heuristic to speed up searching. We end up using the highest valued heuristic for expansion and this helps encourage the search in valid directions to hit the right orientation rather than just being close in distance proximity.

This was a key item from the paper to getting realtime performance

**Comment by SteveMacenski** [comment]
Per #5 


I believe the 2 remaining bad cases [loop-de-loop and jumping branches] may be related to the bad heuristic computation that needs to be updated for the SE2 node (not just distance based). We dont yet have the 2 lookup table heuristics available yet, and this is mostly a problem closer to the goal so I think that tells me that this is primarily heuristic based. Because the hueristic is incorrect, the order in the priority queue is wrong, so it may be jumping to other trees of lower cost purely because moderately closer. This doesn't account for the cost getting there of turnign too much or bad motion that the 2 heuristics would punish.

Once one or both are in place, then we should check for this to be gone

**Comment by james-ward** [comment]
I'm going to start work on this.
